/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import master.*;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import setting.formatMataUang;
import javax.swing.JTextField;
import uniqid.uniqid;
import proses.tsukamoto;
/**
 *
 * @author imam
 */
public class menuUtama extends javax.swing.JFrame {
    produksi produksi;
    kriteria kriteria;
    rule rule;
    formatMataUang fmu;
    uniqid uniqid;
    tsukamoto tsukamoto;
    detailPerhitungan detail;
    
    DefaultTableModel modelProduksi;
    String[] headerTbProduksi = {"No.","Kode Produksi","Bulan","Permintaan","Persediaan","Event","Produksi"};
    DefaultTableModel modelKriteria;
    String[] headerTbKriteria = {"No.","Kode Kriteria","Nama Kriteria","Rentang","Min","Max"};
    DefaultTableModel modelRule;
    String[] headerRule = {"No.","Kode Rule","Permintaan","Persediaan","Event","Produksi"};
    DefaultTableModel modelProsesKriteria;
    String[] headerProsesKriteria = {"No.","Nama Kriteria","Rentang","Min","Max"};
    DefaultTableModel modelProsesRule;
    String[] headerProsesRule = {"No.","Permintaan","Persediaan","Event","Produksi"};
    DefaultTableModel modelRekap;
    String[] headerRekap = {"No.","Bulan","Permintaan","Persediaan","Event","Target","Aktual"};
    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        initComponents();
        awal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEventProduksi = new javax.swing.ButtonGroup();
        bgRuleEvent = new javax.swing.ButtonGroup();
        bgProsesEvent = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelMenuRekapHasil = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        panelMenuTsukamoto = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelMenuRule = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panelMenuKriteria = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panelMenuProduksi = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelMenuBeranda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelTengah = new javax.swing.JPanel();
        panelBeranda = new javax.swing.JPanel();
        panelMasterProduk = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtBulan = new javax.swing.JTextField();
        txtKodeProduksi = new javax.swing.JTextField();
        txtPersediaan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPermintaan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rbEventLow = new javax.swing.JRadioButton();
        rbEventHigh = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        txtProduksi = new javax.swing.JTextField();
        btnSimpanProduksi = new javax.swing.JButton();
        btnClearProduksi = new javax.swing.JButton();
        btnHapusProduksi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduksi = new javax.swing.JTable();
        lbJmlProduk = new javax.swing.JLabel();
        panelMasterKriteria = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        txtNamaKriteria = new javax.swing.JTextField();
        txtKodeKriteria = new javax.swing.JTextField();
        txtMin = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtRentang = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        btnSimpanKriteria = new javax.swing.JButton();
        btnClearKriteria = new javax.swing.JButton();
        btnHapusKriteria = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKriteria = new javax.swing.JTable();
        lbJmlKriteria = new javax.swing.JLabel();
        panelMasterRule = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtRulePermintaan = new javax.swing.JTextField();
        txtKodeRule = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtRulePersediaan = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        rbRuleEventLow = new javax.swing.JRadioButton();
        rbRuleEventHigh = new javax.swing.JRadioButton();
        jLabel36 = new javax.swing.JLabel();
        txtRuleProduksi = new javax.swing.JTextField();
        btnSimpanRule = new javax.swing.JButton();
        btnClearRule = new javax.swing.JButton();
        btnHapusRule = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbRule = new javax.swing.JTable();
        lbJmlRule = new javax.swing.JLabel();
        panelProsesTsukamoto = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtProsesPermintaan = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtProsesPersediaan = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        rbProsesEventLow = new javax.swing.JRadioButton();
        rbProsesEventHigh = new javax.swing.JRadioButton();
        btnProsesTsukamoto = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        txtProsesBulan = new javax.swing.JTextField();
        btnClearProses = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbProsesRule = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbProsesKriteria = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtHasilProses = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        panelHasilRekap = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbRekap = new javax.swing.JTable();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(233, 226, 226));
        jPanel1.setPreferredSize(new java.awt.Dimension(1370, 771));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(220, 239, 201));
        panelHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("SINAR REJOSARI TERANG");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 420, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("-");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 30, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panelHeader.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 30, 30));

        jPanel1.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 30));

        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuRekapHasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenuRekapHasil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("REKAP HASIL PREDIKSI");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        panelMenuRekapHasil.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(panelMenuRekapHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 30));

        panelMenuTsukamoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenuTsukamoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setText("Tsukamoto");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        panelMenuTsukamoto.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(panelMenuTsukamoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 30));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("PROSES");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 30));

        panelMenuRule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenuRule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Rule");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        panelMenuRule.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(panelMenuRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 30));

        panelMenuKriteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenuKriteria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Kriteria");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panelMenuKriteria.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(panelMenuKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 30));

        panelMenuProduksi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenuProduksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Produk");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panelMenuProduksi.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(panelMenuProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("MASTER");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("M E N U");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 50));

        panelMenuBeranda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panelMenuBeranda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("BERANDA");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelMenuBeranda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 210, 30));

        panelMenu.add(panelMenuBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 30));

        jPanel1.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 740));

        panelTengah.setBackground(new java.awt.Color(255, 255, 255));
        panelTengah.setLayout(new java.awt.CardLayout());

        panelBeranda.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelBerandaLayout = new javax.swing.GroupLayout(panelBeranda);
        panelBeranda.setLayout(panelBerandaLayout);
        panelBerandaLayout.setHorizontalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        panelBerandaLayout.setVerticalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        panelTengah.add(panelBeranda, "card2");

        panelMasterProduk.setBackground(new java.awt.Color(255, 255, 255));
        panelMasterProduk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelMasterProduk.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1030, 10));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Data Produk");
        panelMasterProduk.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1120, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Event                :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));
        jPanel2.add(txtBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));
        jPanel2.add(txtKodeProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, -1));

        txtPersediaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPersediaanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPersediaanKeyTyped(evt);
            }
        });
        jPanel2.add(txtPersediaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 200, -1));

        jLabel15.setText("Bulan                :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        txtPermintaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPermintaanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPermintaanKeyTyped(evt);
            }
        });
        jPanel2.add(txtPermintaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 200, -1));

        jLabel16.setText("Permintaan       :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel17.setText("Persediaan        :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        rbEventLow.setBackground(new java.awt.Color(255, 255, 255));
        bgEventProduksi.add(rbEventLow);
        rbEventLow.setText("Low");
        jPanel2.add(rbEventLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        rbEventHigh.setBackground(new java.awt.Color(255, 255, 255));
        bgEventProduksi.add(rbEventHigh);
        rbEventHigh.setText("High");
        jPanel2.add(rbEventHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel18.setText("Produksi            :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        txtProduksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProduksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProduksiKeyTyped(evt);
            }
        });
        jPanel2.add(txtProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 200, -1));

        btnSimpanProduksi.setText("Simpan");
        btnSimpanProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanProduksiActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpanProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        btnClearProduksi.setText("Clear");
        btnClearProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearProduksiActionPerformed(evt);
            }
        });
        jPanel2.add(btnClearProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        btnHapusProduksi.setText("Hapus");
        btnHapusProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProduksiActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapusProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        panelMasterProduk.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 220));

        tbProduksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProduksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProduksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduksi);

        panelMasterProduk.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 770, 590));

        lbJmlProduk.setText("jLabel19");
        panelMasterProduk.add(lbJmlProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, 200, 30));

        panelTengah.add(panelMasterProduk, "card3");

        panelMasterKriteria.setBackground(new java.awt.Color(255, 255, 255));
        panelMasterKriteria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelMasterKriteria.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1030, 10));

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Data Kriteria");
        panelMasterKriteria.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1120, 50));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(txtNamaKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 210, -1));
        jPanel11.add(txtKodeKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 210, -1));

        txtMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMinKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMinKeyTyped(evt);
            }
        });
        jPanel11.add(txtMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 210, -1));

        jLabel21.setText("Nama Kriteria    :");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));
        jPanel11.add(txtRentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 210, -1));

        jLabel22.setText("Rentang            :");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel23.setText("Min                    :");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel24.setText("Max                   :");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        txtMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMaxKeyTyped(evt);
            }
        });
        jPanel11.add(txtMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, -1));

        btnSimpanKriteria.setText("Simpan");
        btnSimpanKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKriteriaActionPerformed(evt);
            }
        });
        jPanel11.add(btnSimpanKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        btnClearKriteria.setText("Clear");
        btnClearKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearKriteriaActionPerformed(evt);
            }
        });
        jPanel11.add(btnClearKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        btnHapusKriteria.setText("Hapus");
        btnHapusKriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKriteriaActionPerformed(evt);
            }
        });
        jPanel11.add(btnHapusKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        panelMasterKriteria.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 190));

        tbKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKriteriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKriteria);

        panelMasterKriteria.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 770, 590));

        lbJmlKriteria.setText("jLabel19");
        panelMasterKriteria.add(lbJmlKriteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, 200, 30));

        panelTengah.add(panelMasterKriteria, "card4");

        panelMasterRule.setBackground(new java.awt.Color(255, 255, 255));
        panelMasterRule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelMasterRule.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1030, 10));

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Data Rule");
        panelMasterRule.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1120, 50));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("Event                :");
        jPanel12.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));
        jPanel12.add(txtRulePermintaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, -1));
        jPanel12.add(txtKodeRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 200, -1));

        jLabel30.setText("Permintaan        :");
        jPanel12.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));
        jPanel12.add(txtRulePersediaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 200, -1));

        jLabel31.setText("Persediaan        :");
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        rbRuleEventLow.setBackground(new java.awt.Color(255, 255, 255));
        bgRuleEvent.add(rbRuleEventLow);
        rbRuleEventLow.setText("Low");
        jPanel12.add(rbRuleEventLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        rbRuleEventHigh.setBackground(new java.awt.Color(255, 255, 255));
        bgRuleEvent.add(rbRuleEventHigh);
        rbRuleEventHigh.setText("High");
        jPanel12.add(rbRuleEventHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel36.setText("Produksi            :");
        jPanel12.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));
        jPanel12.add(txtRuleProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 200, -1));

        btnSimpanRule.setText("Simpan");
        btnSimpanRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanRuleActionPerformed(evt);
            }
        });
        jPanel12.add(btnSimpanRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        btnClearRule.setText("Clear");
        btnClearRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearRuleActionPerformed(evt);
            }
        });
        jPanel12.add(btnClearRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        btnHapusRule.setText("Hapus");
        btnHapusRule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusRuleActionPerformed(evt);
            }
        });
        jPanel12.add(btnHapusRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        panelMasterRule.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 180));

        tbRule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbRule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRuleMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbRule);

        panelMasterRule.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 770, 590));

        lbJmlRule.setText("jLabel19");
        panelMasterRule.add(lbJmlRule, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, 200, 30));

        panelTengah.add(panelMasterRule, "card5");

        panelProsesTsukamoto.setBackground(new java.awt.Color(255, 255, 255));
        panelProsesTsukamoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setText("Event                :");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        txtProsesPermintaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProsesPermintaanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProsesPermintaanKeyTyped(evt);
            }
        });
        jPanel13.add(txtProsesPermintaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, -1));

        jLabel37.setText("Permintaan        :");
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        txtProsesPersediaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProsesPersediaanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProsesPersediaanKeyTyped(evt);
            }
        });
        jPanel13.add(txtProsesPersediaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 210, -1));

        jLabel38.setText("Persediaan        :");
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        rbProsesEventLow.setBackground(new java.awt.Color(255, 255, 255));
        bgProsesEvent.add(rbProsesEventLow);
        rbProsesEventLow.setText("Low");
        rbProsesEventLow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbProsesEventLowMouseClicked(evt);
            }
        });
        jPanel13.add(rbProsesEventLow, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        rbProsesEventHigh.setBackground(new java.awt.Color(255, 255, 255));
        bgProsesEvent.add(rbProsesEventHigh);
        rbProsesEventHigh.setText("High");
        rbProsesEventHigh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbProsesEventHighMouseClicked(evt);
            }
        });
        jPanel13.add(rbProsesEventHigh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        btnProsesTsukamoto.setText("Proses");
        btnProsesTsukamoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesTsukamotoActionPerformed(evt);
            }
        });
        jPanel13.add(btnProsesTsukamoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel39.setText("Bulan                 :");
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));
        jPanel13.add(txtProsesBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 210, -1));

        btnClearProses.setText("Clear");
        btnClearProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearProsesActionPerformed(evt);
            }
        });
        jPanel13.add(btnClearProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        panelProsesTsukamoto.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 320, 180));
        panelProsesTsukamoto.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1030, 10));

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Proses Tsukamoto");
        panelProsesTsukamoto.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1120, 50));

        tbProsesRule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbProsesRule);

        panelProsesTsukamoto.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 380, 570));

        tbProsesKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbProsesKriteria);

        panelProsesTsukamoto.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 380, 570));

        txtHasilProses.setColumns(20);
        txtHasilProses.setRows(5);
        jScrollPane6.setViewportView(txtHasilProses);

        panelProsesTsukamoto.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 320, 340));

        jButton7.setText("Proses semua data produksi");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelProsesTsukamoto.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jButton8.setText("Detail Perhitungan");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelProsesTsukamoto.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 660, 140, -1));

        panelTengah.add(panelProsesTsukamoto, "card6");

        panelHasilRekap.setBackground(new java.awt.Color(255, 255, 255));
        panelHasilRekap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbRekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbRekap);

        panelHasilRekap.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 70, 1090, 610));
        panelHasilRekap.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1030, 10));

        jLabel41.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Rekap Hasil Prediksi");
        panelHasilRekap.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1120, 50));

        panelTengah.add(panelHasilRekap, "card7");

        jPanel1.add(panelTengah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 1120, 700));

        jLabel13.setText("Selamat Datang!");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 270, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void awal(){
        produksi = new produksi();
        kriteria = new kriteria();
        rule = new rule();
        fmu = new formatMataUang();
        uniqid = new uniqid();
        detail = new detailPerhitungan(this, false);
        tsukamoto = new tsukamoto(this, detail);
        
        showPanelTengah(panelBeranda, "beranda");
        
        // model
        modelProduksi = new DefaultTableModel(headerTbProduksi, 0){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;
            }
        };
        tbProduksi.setModel(modelProduksi);
        modelKriteria = new DefaultTableModel(headerTbKriteria, 0){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;
            }
        };
        tbKriteria.setModel(modelKriteria);
        modelRule = new DefaultTableModel(headerRule, 0){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;
            }
        };
        tbRule.setModel(modelRule);
        modelProsesKriteria = new DefaultTableModel(headerProsesKriteria, 0){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;
            }
        };
        tbProsesKriteria.setModel(modelProsesKriteria);
        modelProsesRule = new DefaultTableModel(headerProsesRule, 0){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;
            }
        };
        tbProsesRule.setModel(modelProsesRule);
        modelRekap = new DefaultTableModel(headerRekap, 0){
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
            return false;
            }
        };
        tbRekap.setModel(modelRekap);
        
        // hide
        txtKodeProduksi.setVisible(false);
        txtKodeKriteria.setVisible(false);
        txtKodeRule.setVisible(false);
        
    }

    public JTextArea getTxtHasilProses() {
        return txtHasilProses;
    }
    
    private void showPanelTengah(JPanel panel, String menu){
        panelTengah.removeAll();
        panelTengah.add(panel);
        panelTengah.repaint();
        panelTengah.revalidate();
        indikator(menu);
    }
    
    private void indikator(String menu){
        Color warnaPilih = new Color(153,102,0);
        Color warnaAsli = new Color(240,240,240);
        if (menu.equals("beranda")) {
            panelMenuBeranda.setBackground(warnaPilih);
        }else{
            panelMenuBeranda.setBackground(warnaAsli);
        }
        if (menu.equals("produksi")) {
            panelMenuProduksi.setBackground(warnaPilih);
        }else{
            panelMenuProduksi.setBackground(warnaAsli);
        }
        if (menu.equals("kriteria")) {
            panelMenuKriteria.setBackground(warnaPilih);
        }else{
            panelMenuKriteria.setBackground(warnaAsli);
        }
        if (menu.equals("rule")) {
            panelMenuRule.setBackground(warnaPilih);
        }else{
            panelMenuRule.setBackground(warnaAsli);
        }
        if (menu.equals("tsukamoto")) {
            panelMenuTsukamoto.setBackground(warnaPilih);
        }else{
            panelMenuTsukamoto.setBackground(warnaAsli);
        }
        if (menu.equals("rekap")) {
            panelMenuRekapHasil.setBackground(warnaPilih);
        }else{
            panelMenuRekapHasil.setBackground(warnaAsli);
        }
    }
    
    private void filterangka(KeyEvent evt){
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || 
                (karakter == KeyEvent.VK_BACK_SPACE) || 
                (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }
    
    private void tampil(DefaultTableModel model, String[][] data){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        if (data != null) {
            for (int i = 0; i < data.length; i++) {
                Object[] ob = new Object[data[i].length];
                for (int j = 0; j < ob.length; j++) {
                    ob[j] = data[i][j];
                }
                model.addRow(ob);
            }
        }
    }
    
    private void formatIndo(JTextField text){
        String angka = text.getText();
        if (!angka.isEmpty()) {
            String rupiah = fmu.formatIndonesia(angka);
            text.setText(rupiah);
        }
    }
    
    private void clearProduksi(){
        txtKodeProduksi.setText(null);
        txtBulan.setText(null);
        txtPermintaan.setText(null);
        txtPersediaan.setText(null);
        txtProduksi.setText(null);
        bgEventProduksi.clearSelection();
        String[][] dataProduksi = produksi.get_all();
        tampil(modelProduksi, dataProduksi);
        btnSimpanProduksi.setText("Simpan");
    }
    
    private void clearKriteria(){
        txtKodeKriteria.setText(null);
        txtNamaKriteria.setText(null);
        txtRentang.setText(null);
        txtMin.setText(null);
        txtMax.setText(null);
        String[][] data = kriteria.get_all();
        tampil(modelKriteria, data);
        btnSimpanKriteria.setText("Simpan");
    }
    
    private void clearRule(){
        txtKodeRule.setText(null);
        txtRulePermintaan.setText(null);
        txtRulePersediaan.setText(null);
        bgRuleEvent.clearSelection();
        txtRuleProduksi.setText(null);
        String[][] data = rule.get_all();
        tampil(modelRule, data);
        btnSimpanRule.setText("Simpan");
    }
    
    private void clearTsukamoto(){
        txtProsesBulan.setText(null);
        txtProsesPermintaan.setText(null);
        txtProsesPersediaan.setText(null);
        bgProsesEvent.clearSelection();
        txtHasilProses.setText(null);
        detail.getTxtDetailProses().setText(null);
        String[][] dataKriteria = kriteria.getKriteria();
        tampil(modelProsesKriteria, dataKriteria);
    }
    
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        showPanelTengah(panelBeranda, "beranda");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        showPanelTengah(panelMasterProduk, "produksi");
        clearProduksi();
        int jml = tbProduksi.getRowCount();
        String jumlah = String.valueOf(jml);
        jumlah = fmu.formatIndonesia(jumlah);
        lbJmlProduk.setText("Jumlah data : "+jumlah);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        showPanelTengah(panelMasterKriteria, "kriteria");
        clearKriteria();
        int jml = tbKriteria.getRowCount();
        String jumlah = String.valueOf(jml);
        jumlah = fmu.formatIndonesia(jumlah);
        lbJmlKriteria.setText("Jumlah data : "+jumlah);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        showPanelTengah(panelMasterRule, "rule");
        clearRule();
        int jml = tbRule.getRowCount();
        String jumlah = String.valueOf(jml);
        jumlah = fmu.formatIndonesia(jumlah);
        lbJmlRule.setText("Jumlah data : "+jumlah);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        showPanelTengah(panelProsesTsukamoto, "tsukamoto");
        clearTsukamoto();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        showPanelTengah(panelHasilRekap, "rekap");
        String[][] data = produksi.getAllRelasiHasil();
        tampil(modelRekap, data);
    }//GEN-LAST:event_jLabel25MouseClicked

    private void btnSimpanProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanProduksiActionPerformed
        // TODO add your handling code here:
        String kode_produksi = txtKodeProduksi.getText();
        String bulan = txtBulan.getText();
        String permintaan = txtPermintaan.getText();
        String persediaan = txtPersediaan.getText();
        String prd = txtProduksi.getText();
        String event = "";
        if (rbEventLow.isSelected()) {
            event = rbEventLow.getText();
        }else if(rbEventHigh.isSelected()){
            event = rbEventHigh.getText();
        }
        if (bulan.isEmpty() || permintaan.isEmpty() || persediaan.isEmpty() || prd.isEmpty() || event.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi data!");
        }else{
            permintaan = fmu.reFormatIndonesia(permintaan);
            persediaan = fmu.reFormatIndonesia(persediaan);
            prd = fmu.reFormatIndonesia(prd);
            if (kode_produksi.isEmpty()) {
                String[][] data = {
                    {"kode_produksi", produksi.autoCode()},
                    {"bln", bulan},
                    {"permintaan", permintaan},
                    {"persediaan", persediaan},
                    {"event", event},
                    {"produksi", prd}
                };
                produksi.save(data);
            }else{
                String[][] data = {
                    {"bln", bulan},
                    {"permintaan", permintaan},
                    {"persediaan", persediaan},
                    {"event", event},
                    {"produksi", prd}
                };
                produksi.edit(data, kode_produksi);
            }
            clearProduksi();
        }
    }//GEN-LAST:event_btnSimpanProduksiActionPerformed

    private void btnClearProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearProduksiActionPerformed
        // TODO add your handling code here:
        clearProduksi();
    }//GEN-LAST:event_btnClearProduksiActionPerformed

    private void txtPermintaanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPermintaanKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_txtPermintaanKeyTyped

    private void txtPermintaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPermintaanKeyReleased
        // TODO add your handling code here:
        formatIndo(txtPermintaan);
    }//GEN-LAST:event_txtPermintaanKeyReleased

    private void txtPersediaanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersediaanKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_txtPersediaanKeyTyped

    private void txtPersediaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersediaanKeyReleased
        // TODO add your handling code here:
        formatIndo(txtPersediaan);
    }//GEN-LAST:event_txtPersediaanKeyReleased

    private void txtProduksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProduksiKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_txtProduksiKeyTyped

    private void txtProduksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProduksiKeyReleased
        // TODO add your handling code here:
        formatIndo(txtProduksi);
    }//GEN-LAST:event_txtProduksiKeyReleased

    private void tbProduksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProduksiMouseClicked
        // TODO add your handling code here:
        int baris = tbProduksi.getSelectedRow();
        String kode_produksi = tbProduksi.getValueAt(baris, 1).toString();
        String bulan = tbProduksi.getValueAt(baris, 2).toString();
        String permintaan = tbProduksi.getValueAt(baris, 3).toString();
        String persediaan = tbProduksi.getValueAt(baris, 4).toString();
        String event = tbProduksi.getValueAt(baris, 5).toString();
        String prd = tbProduksi.getValueAt(baris, 6).toString();
        txtKodeProduksi.setText(kode_produksi);
        txtBulan.setText(bulan);
        permintaan = fmu.reFormatIndonesia(permintaan);
        permintaan = fmu.formatIndonesia(permintaan);
        txtPermintaan.setText(permintaan);
        persediaan = fmu.reFormatIndonesia(persediaan);
        persediaan = fmu.formatIndonesia(persediaan);
        txtPersediaan.setText(persediaan);
        if (event.equals(rbEventLow.getText())) {
            rbEventLow.setSelected(true);
        }else{
            rbEventHigh.setSelected(true);
        }
        prd = fmu.reFormatIndonesia(prd);
        prd = fmu.formatIndonesia(prd);
        txtProduksi.setText(prd);
        btnSimpanProduksi.setText("Ubah");
    }//GEN-LAST:event_tbProduksiMouseClicked

    private void txtMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_txtMinKeyTyped

    private void txtMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinKeyReleased
        // TODO add your handling code here:
        formatIndo(txtMin);
    }//GEN-LAST:event_txtMinKeyReleased

    private void txtMaxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_txtMaxKeyTyped

    private void txtMaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxKeyReleased
        // TODO add your handling code here:
        formatIndo(txtMax);
    }//GEN-LAST:event_txtMaxKeyReleased

    private void btnSimpanKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKriteriaActionPerformed
        // TODO add your handling code here:
        String kode_kriteria = txtKodeKriteria.getText();
        String nama_kritetia = txtNamaKriteria.getText();
        String rentang = txtRentang.getText();
        String min = txtMin.getText();
        String max = txtMax.getText();
        if (nama_kritetia.isEmpty() || rentang.isEmpty() || min.isEmpty() || max.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi daata!");
        }else{
            min = fmu.reFormatIndonesia(min);
            max = fmu.reFormatIndonesia(max);
            if (kode_kriteria.isEmpty()) {
                String[][] data = {
                    {"kode_kriteria", uniqid.get()},
                    {"nama_kriteria", nama_kritetia},
                    {"rentang", rentang},
                    {"min", min},
                    {"max", max}
                };
                kriteria.save(data);
            }else{
                String[][] data = {
                    {"nama_kriteria", nama_kritetia},
                    {"rentang", rentang},
                    {"min", min},
                    {"max", max}
                };
                kriteria.edit(data, kode_kriteria);
            }
            clearKriteria();
        }
    }//GEN-LAST:event_btnSimpanKriteriaActionPerformed

    private void tbKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKriteriaMouseClicked
        // TODO add your handling code here:
        int baris = tbKriteria.getSelectedRow();
        String kode_kriteria = tbKriteria.getValueAt(baris, 1).toString();
        String nama_kriteria = tbKriteria.getValueAt(baris, 2).toString();
        String rentang = tbKriteria.getValueAt(baris, 3).toString();
        String min = tbKriteria.getValueAt(baris, 4).toString();
        String max = tbKriteria.getValueAt(baris, 5).toString();
        min = fmu.reFormatIndonesia(min);
        max = fmu.reFormatIndonesia(max);
        min = fmu.formatIndonesia(min);
        max = fmu.formatIndonesia(max);
        txtKodeKriteria.setText(kode_kriteria);
        txtNamaKriteria.setText(nama_kriteria);
        txtRentang.setText(rentang);
        txtMin.setText(min);
        txtMax.setText(max);
        btnSimpanKriteria.setText("Ubah");
    }//GEN-LAST:event_tbKriteriaMouseClicked

    private void btnHapusProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProduksiActionPerformed
        // TODO add your handling code here:
        String kode_produksi = txtKodeProduksi.getText();
        if (kode_produksi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
        }else{
            produksi.delete(kode_produksi);
            clearProduksi();
        }
    }//GEN-LAST:event_btnHapusProduksiActionPerformed

    private void btnClearKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearKriteriaActionPerformed
        // TODO add your handling code here:
        clearKriteria();
    }//GEN-LAST:event_btnClearKriteriaActionPerformed

    private void btnHapusKriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKriteriaActionPerformed
        // TODO add your handling code here:
        String kode_kriteria = txtKodeKriteria.getText();
        if (kode_kriteria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "pilih data yang akan dihapus!");
        }else{
            kriteria.delete(kode_kriteria);
            clearKriteria();
        }
    }//GEN-LAST:event_btnHapusKriteriaActionPerformed

    private void tbRuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRuleMouseClicked
        // TODO add your handling code here:
        int baris = tbRule.getSelectedRow();
        String kode_rule = tbRule.getValueAt(baris, 1).toString();
        String permintaan = tbRule.getValueAt(baris, 2).toString();
        String persediaan = tbRule.getValueAt(baris, 3).toString();
        String event = tbRule.getValueAt(baris, 4).toString();
        String prd = tbRule.getValueAt(baris, 5).toString();
        if (event.equals(rbRuleEventLow.getText())) {
            rbRuleEventLow.setSelected(true);
        }else{
            rbRuleEventHigh.setSelected(true);
        }
        txtKodeRule.setText(kode_rule);
        txtRulePermintaan.setText(permintaan);
        txtRulePersediaan.setText(persediaan);
        txtRuleProduksi.setText(prd);
        btnSimpanRule.setText("Ubah");
    }//GEN-LAST:event_tbRuleMouseClicked

    private void btnClearRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearRuleActionPerformed
        // TODO add your handling code here:
        clearRule();
    }//GEN-LAST:event_btnClearRuleActionPerformed

    private void btnHapusRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusRuleActionPerformed
        // TODO add your handling code here:
        String kode_rule = txtKodeRule.getText();
        if (kode_rule.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
        }else{
            rule.delete(kode_rule);
            clearRule();
        }
    }//GEN-LAST:event_btnHapusRuleActionPerformed

    private void btnSimpanRuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanRuleActionPerformed
        // TODO add your handling code here:
        String kode_rule = txtKodeRule.getText();
        String permintaan = txtRulePermintaan.getText();
        String persediaan = txtRulePersediaan.getText();
        String prd = txtRuleProduksi.getText();
        String event = "";
        if (rbRuleEventLow.isSelected()) {
            event = rbRuleEventLow.getText();
        }else if(rbRuleEventHigh.isSelected()){
            event = rbRuleEventHigh.getText();
        }
        if (permintaan.isEmpty() || persediaan.isEmpty() || event.isEmpty() || prd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi data!");
        }else{
            if (kode_rule.isEmpty()) {
                String[][] data = {
                    {"kode_rule", uniqid.get()},
                    {"permintaan", permintaan},
                    {"persediaan", persediaan},
                    {"event", event},
                    {"produksi", prd}
                };
                rule.save(data);
            }else{
                String[][] data = {
                    {"permintaan", permintaan},
                    {"persediaan", persediaan},
                    {"event", event},
                    {"produksi", prd}
                };
                rule.edit(data, kode_rule);
            }
            clearRule();
        }
    }//GEN-LAST:event_btnSimpanRuleActionPerformed

    private void rbProsesEventLowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbProsesEventLowMouseClicked
        // TODO add your handling code here:
        boolean pilih = rbProsesEventLow.isSelected();
        if (pilih) {
            String event = rbProsesEventLow.getText();
            String[][] data = rule.getRule(event);
            tampil(modelProsesRule, data);
        }
    }//GEN-LAST:event_rbProsesEventLowMouseClicked

    private void rbProsesEventHighMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbProsesEventHighMouseClicked
        // TODO add your handling code here:
        boolean pilih = rbProsesEventHigh.isSelected();
        if (pilih) {
            String event = rbProsesEventHigh.getText();
            String[][] data = rule.getRule(event);
            tampil(modelProsesRule, data);
        }
    }//GEN-LAST:event_rbProsesEventHighMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        detail.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String[][] data = tsukamoto.hitungSemua();
        tsukamoto.simpan(data);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnClearProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearProsesActionPerformed
        // TODO add your handling code here:
        clearTsukamoto();
    }//GEN-LAST:event_btnClearProsesActionPerformed

    private void btnProsesTsukamotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesTsukamotoActionPerformed
        // TODO add your handling code here:
        String bulan = txtProsesBulan.getText();
        String permintaan = txtProsesPermintaan.getText();
        String persediaan = txtProsesPersediaan.getText();
        String event = "";
        if (rbProsesEventHigh.isSelected()) {
            event = rbProsesEventHigh.getText();
        }else if (rbProsesEventLow.isSelected()) {
            event = rbProsesEventLow.getText();
        }
        if (bulan.isEmpty() || permintaan.isEmpty() || persediaan.isEmpty() || event.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi data!");
        }else{
            permintaan = fmu.reFormatIndonesia(permintaan);
            persediaan = fmu.reFormatIndonesia(persediaan);
            double pmt = Double.parseDouble(permintaan);
            double psd = Double.parseDouble(persediaan);
            tsukamoto.hitung(bulan, pmt, psd, event);
        }
    }//GEN-LAST:event_btnProsesTsukamotoActionPerformed

    private void txtProsesPermintaanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProsesPermintaanKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_txtProsesPermintaanKeyTyped

    private void txtProsesPermintaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProsesPermintaanKeyReleased
        // TODO add your handling code here:
        formatIndo(txtProsesPermintaan);
    }//GEN-LAST:event_txtProsesPermintaanKeyReleased

    private void txtProsesPersediaanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProsesPersediaanKeyTyped
        // TODO add your handling code here:
        filterangka(evt);
    }//GEN-LAST:event_txtProsesPersediaanKeyTyped

    private void txtProsesPersediaanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProsesPersediaanKeyReleased
        // TODO add your handling code here:
        formatIndo(txtProsesPersediaan);
    }//GEN-LAST:event_txtProsesPersediaanKeyReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuUtama().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEventProduksi;
    private javax.swing.ButtonGroup bgProsesEvent;
    private javax.swing.ButtonGroup bgRuleEvent;
    private javax.swing.JButton btnClearKriteria;
    private javax.swing.JButton btnClearProduksi;
    private javax.swing.JButton btnClearProses;
    private javax.swing.JButton btnClearRule;
    private javax.swing.JButton btnHapusKriteria;
    private javax.swing.JButton btnHapusProduksi;
    private javax.swing.JButton btnHapusRule;
    private javax.swing.JButton btnProsesTsukamoto;
    private javax.swing.JButton btnSimpanKriteria;
    private javax.swing.JButton btnSimpanProduksi;
    private javax.swing.JButton btnSimpanRule;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbJmlKriteria;
    private javax.swing.JLabel lbJmlProduk;
    private javax.swing.JLabel lbJmlRule;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelHasilRekap;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMasterKriteria;
    private javax.swing.JPanel panelMasterProduk;
    private javax.swing.JPanel panelMasterRule;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMenuBeranda;
    private javax.swing.JPanel panelMenuKriteria;
    private javax.swing.JPanel panelMenuProduksi;
    private javax.swing.JPanel panelMenuRekapHasil;
    private javax.swing.JPanel panelMenuRule;
    private javax.swing.JPanel panelMenuTsukamoto;
    private javax.swing.JPanel panelProsesTsukamoto;
    private javax.swing.JPanel panelTengah;
    private javax.swing.JRadioButton rbEventHigh;
    private javax.swing.JRadioButton rbEventLow;
    private javax.swing.JRadioButton rbProsesEventHigh;
    private javax.swing.JRadioButton rbProsesEventLow;
    private javax.swing.JRadioButton rbRuleEventHigh;
    private javax.swing.JRadioButton rbRuleEventLow;
    private javax.swing.JTable tbKriteria;
    private javax.swing.JTable tbProduksi;
    private javax.swing.JTable tbProsesKriteria;
    private javax.swing.JTable tbProsesRule;
    private javax.swing.JTable tbRekap;
    private javax.swing.JTable tbRule;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextArea txtHasilProses;
    private javax.swing.JTextField txtKodeKriteria;
    private javax.swing.JTextField txtKodeProduksi;
    private javax.swing.JTextField txtKodeRule;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtNamaKriteria;
    private javax.swing.JTextField txtPermintaan;
    private javax.swing.JTextField txtPersediaan;
    private javax.swing.JTextField txtProduksi;
    private javax.swing.JTextField txtProsesBulan;
    private javax.swing.JTextField txtProsesPermintaan;
    private javax.swing.JTextField txtProsesPersediaan;
    private javax.swing.JTextField txtRentang;
    private javax.swing.JTextField txtRulePermintaan;
    private javax.swing.JTextField txtRulePersediaan;
    private javax.swing.JTextField txtRuleProduksi;
    // End of variables declaration//GEN-END:variables
}
